config/routes.rb
Rails.application.routes.draw do
  resources :flight
  resources :bookings
  resources :passengers, only: :new
  root to: 'flights#index'
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :outgoing_flights, foreign_key: "origin_id", class_name: "Flight"
  has_many :incoming_flights, foreign_key: "destination_id", class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :origin, foreign_key: "origin_id", class_name: "Airport"
  belongs_to :destination, foreign_key: "destination_id", class_name: "Airport"
  has_many :bookings
def format_date
end

end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end
  
  def new
    @flight = Flight.find(params[:flight_id])
    @booking = Booking.new
    params[:passengers].to_i.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      passengers = @booking.passengers.all

      passengers.each do |passenger|
        BookingMailer.new_booking(@booking, passenger).deliver_now
      end

      flash[:success] = "Flight Booked!"
      redirect_to booking_path(id: @booking.id)
    else
      render action: :new
    end
  end


  private
    def booking_params
      params.require(:booking).permit(
        :flight_id,
        :date,
        :origin_city,
        :destination_city,
        passengers_attributes: [:name, :email]
      )
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    
    @airport_options = Airport.all.map { |a| [a.city, a.id] }
    @date_options = Flight.all.map { |d| [d.date.strftime("%m/%d/%Y"), d.date] }.uniq

    if params
      @flights = Flight.where(
        origin_id: params[:origin_id],
        destination_id: params[:destination_id],
        date: params[:date]
      )
    end
  end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <%= form_with(model: @booking, local: true) do |f| %>
        <div class="row g-2">
          <div class="col-md-6">
            <%= f.label :flight_id, "Flight Number", class: "form-label" %>
            <%= f.text_field :flight_id, value: params[:flight_id], readonly: true, class: "form-control" %>
          </div>
          <div class="col-md-6">
            <%= f.label :date, class: "form-label" %>
            <%= f.text_field :date, value: params[:date], readonly: true, class: "form-control" %>
          </div>
          <div class="col-md-6">
            <%= f.label :origin_city, "Outing Airport", class: "form-label" %>
            <%= f.text_field :origin_city, value: params[:origin_city], readonly: true, class: "form-control" %>
          </div>
          <div class="col-md-6">
            <%= f.label :destination_city, "Destination Airport", class: "form-label" %>
            <%= f.text_field :destination_city, value: params[:destination_city], readonly: true, class: "form-control" %>
          </div>

          <div class="col mt-3">
            <h4>Passenger Information</h4>
            <%= f.fields_for :passengers do |passenger_form| %>
              <div class="row g-3">
                <div class="col-md-6">
                  <%= passenger_form.label :name, class: "form-label" %>
                  <%= passenger_form.text_field :name, class: "form-control" %>
                </div>
                <div class="col-md-6">
                  <%= passenger_form.label :email, class: "form-label" %>
                  <%= passenger_form.text_field :email, class: "form-control" %>
                </div>
              </div>
            <% end %>
          </div>

          <div class="row g-2 mt-2">
            <div class="col-auto">
              <%= submit_tag 'Book Tickets', name: nil, class: "btn btn-primary" %>
            </div>
            <div class="col-md-1">
              <%= link_to "Cancel", root_path, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-6 mx-auto">
      <div class="card">
        <h1 class="text-center">Booking Information</h1>
        <div class="col-md-6 offset-md-4">
        <p class="fs-5">Outgoing: <%= @booking.origin_city %></p>
        <p class="fs-5">Destination: <%= @booking.destination_city %></p>
        <p class="fs-5">Date: <%= @booking.flight.date.strftime("%D") %></p>
        <p class="fs-5">Departure Time: <%= @booking.flight.departure_time.strftime("%I:%M:%S %p") %></p>
        <h4>Passenger Information</h4>
        <% @booking.passengers.each do |passenger| %>
          <p class="fs-5">Name: <%= passenger.name %> - Email: <%= passenger.email %></p>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="d-flex justify-content-center mt-5">
    <%= image_tag("logo/biplane.png")%>
  </div>
  <div class="d-flex justify-content-center mt-3">
    <h5 class="logo-font">Happy Flying</h5>
  </div>
</div>

app/views/flights/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <%= form_with(url: root_path, method: :get, local: true) do |f| %>
        <div class="row g-2">
        <%= hidden_field_tag :index, "true" %>
          <div class="col">
            <%= select_tag(:origin_id, options_for_select(@airport_options), prompt: "From ", required: true, class: "form-select") %>
          </div>

          <div class="col">
            <%= select_tag(:destination_id, options_for_select(@airport_options), prompt: "To ", required: true, class: "form-select") %>
          </div>

          <div class="col">
            <%= f.text_field :passengers, placeholder: "Passengers", class: "form-control" %>
          </div>

          <div class="col">
            <%= select_tag(:date, options_for_select(@date_options), prompt: "Date ", required: true, class: "form-select") %>
          </div>

          <div class="col">
            <%= submit_tag 'Find Flights', name: nil, class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <br>
  <% if params.has_key?(:origin_id) %>
    <div class="container-fluid pt-5 mx-auto">
      <div class="row">
        <div class="col-md-9 offset-md-1">
          <table class="table">
            <thead>
              <th scope="col text-center">Departing From</th>
              <th scope="col">Arriving At</th>
              <th scope="col">Flight Duration</th>
              <th class="th-sm" scope="col">Departure Time</th>
              <th class="th-sm" scope="col"></th>
            </thead>
            <tbody>
              <% @flights.each do |flight| %>
                <%= form_with(url: new_booking_path, method: :get, local: :true) do |f| %>
                  <%= f.hidden_field :passengers, value: params[:passengers] %>
                  <%= f.hidden_field :flight_id, value: flight.id %>
                  <%= f.hidden_field :date, value: flight.date.strftime("%m/%d/%y") %>
                  <tr>
                    <td>
                      <%= f.hidden_field :origin_city, value: flight.origin.city %>
                      <%= flight.origin.city %>
                    </td>
                    <td>
                      <%= f.hidden_field :destination_city, value: flight.destination.city %>
                      <%= flight.destination.city %>
                    </td>
                    <td><%= flight.duration %> Minutes</td>
                    <td><%= flight.departure_time.strftime("%I:%M:%S %p") %></td>
                    <td colspan="1"><%= submit_tag 'Book Flight', name: nil, class: "btn btn-primary" %></td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Oleo+Script:wght@400;700&display=swap" rel="stylesheet">    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="page-container">
      <nav class="navbar navbar-expand-lg navbar-light bg-nav mb-5">
        <div class="container-fluid">
          <%= link_to '/', class: "navbar-brand" do %>
            <%= image_tag("logo/biplane.png", size: "64x38") %>
            <span class="ps-1 logo-font"><b>Simply Flights</b></span>
          <% end %>
        </div>
      </nav>

      <div id="content-wrap">
        <%= yield %>
      </div>

      <footer id="footer">
        <div class="text-muted text-center">Created by: Sean Riedl - <%= link_to "Personal Site", "http://www.sean-blog.com/"%> - <%= link_to "Github", "https://github.com/seanmr7" %></div>
      </footer>
    </div>
  </body>
</html>